const pages=[
['cover','01 / 20','uma história que eu queria te contar','<h2>para<br><i>Alissa</i></h2><div class="rule"></div><p class="cover-note">desça devagar.<br>eu fiz cada página pensando em você.</p><p class="scroll">continue</p>'],
['photo','02 / 20','01 — o começo','<h2>antes de tudo,<br><i>existia uma conversa.</i></h2><figure class="polaroid"><div class="photo" data-src="assets/images/foto-01.jpg">foto 01</div><small>19.07.2026</small></figure><p class="note">e eu ainda não sabia o quanto aquele dia ia significar para mim.</p>'],
['date','03 / 20','02 — uma data','<div class="two-col"><div><span class="giant">19<br><small>julho</small><br>2026</span></div><div class="note"><p>algumas datas passam pelo calendário.</p><p>essa ficou.</p><i>foi aqui que começou.</i></div></div>'],
['letter','04 / 20','03 — uma carta','<article class="letter"><p>alissa,</p><p>eu poderia tentar explicar exatamente quando comecei a gostar de você. mas, pensando bem, acho que não aconteceu em um instante.</p><p>foi aos poucos. em cada conversa, em cada detalhe, em cada vontade de continuar falando mesmo quando já não havia assunto.</p><p>quando percebi, você já tinha virado uma das partes mais bonitas dos meus dias.</p><p class="sign">com carinho,<br><i>eu.</i></p></article>'],
['gallery','05 / 20','04 — alguns dos meus momentos favoritos','<h2>pequenas coisas<br><i>que ficaram.</i></h2><div class="gallery"><figure class="tile tall"><div class="photo" data-src="assets/images/foto-02.jpg">foto 02</div><figcaption>um dia qualquer</figcaption></figure><figure class="tile"><div class="photo" data-src="assets/images/foto-03.jpg">foto 03</div><figcaption>um momento nosso</figcaption></figure><figure class="tile"><div class="photo" data-src="assets/images/foto-04.jpg">foto 04</div><figcaption>e outro</figcaption></figure></div>'],
['quote','06 / 20','05 — uma coisa que eu queria que você soubesse','<div class="quote"><span class="quote-mark">“</span><blockquote>eu gosto da forma como você faz o comum parecer especial.</blockquote><p>e talvez seja exatamente isso que eu mais gosto em nós.</p></div>'],
['timeline','07 / 20','06 — nossa linha do tempo','<h2>do primeiro<br><i>“oi”</i> até aqui.</h2><div class="timeline"><div class="time"><span>19.07</span><div><b>o começo</b><p>a primeira conversa que eu não queria que acabasse.</p></div></div><div class="time"><span>depois</span><div><b>mais conversas</b><p>e a vontade de te conhecer cada vez mais.</p></div></div><div class="time"><span>hoje</span><div><b>você</b><p>uma pessoa que eu quero por perto de verdade.</p></div></div></div>'],
['film','08 / 20','07 — se a nossa história fosse um filme','<div class="film"><div class="video"><span>seu vídeo aqui<br><small>adicione assets/videos/video-01.mp4</small></span></div><div class="film-caption"><span>cena favorita</span><span>sem data de término</span></div></div><p class="note">algumas cenas eu queria poder guardar para sempre.</p>'],
['playlist','09 / 20','08 — trilha sonora','<h2>músicas que<br><i>me lembram você.</i></h2><div class="record-wrap"><div class="record"></div><button id="musicBtn" class="music">tocar música</button></div><audio id="music" loop><source src="assets/music/nossa-musica.mp3" type="audio/mpeg"></audio><p class="help">coloque sua música em assets/music/nossa-musica.mp3</p>'],
['words','10 / 20','09 — coisas que eu penso','<div class="words"><span>seu jeito.</span><span>sua risada.</span><span>nossas conversas.</span><span>a paz que você me traz.</span><span class="mark">você.</span></div>'],
['collage','11 / 20','10 — recortes de nós','<div class="collage"><div class="card c1"><div class="photo" data-src="assets/images/foto-05.jpg">foto 05</div><span>gosto desse.</span></div><div class="card c2"><div class="photo" data-src="assets/images/foto-06.jpg">foto 06</div><span>muito desse.</span></div><div class="card c3"><div class="photo" data-src="assets/images/foto-07.jpg">foto 07</div><span>esse eu guardaria.</span></div><div class="collage-note">para lembrar<br>dos detalhes.</div></div>'],
['count','12 / 20','11 — desde aquele dia','<div class="counters"><div><strong id="days">0</strong><span>dias</span></div><div><strong id="hours">0</strong><span>horas</span></div><div><strong id="mins">0</strong><span>minutos</span></div></div><p class="note">e eu espero que isso seja só o começo.</p>'],
['why','13 / 20','12 — por quê você?','<div class="why"><p><span>01</span>porque com você eu posso ser eu.</p><p><span>02</span>porque você me faz querer ficar.</p><p><span>03</span>porque eu gosto de construir coisas bonitas com você.</p><p><span>04</span>porque, no fim, é você quem eu escolho.</p></div>'],
['full','14 / 20','13 — um dos meus registros favoritos','<div class="full-photo"><div class="photo" data-src="assets/images/foto-08.jpg">sua foto favorita aqui</div></div><div class="overlay"><span>capítulo 13</span><h2>e eu ainda<br><i>tenho muito a viver com você.</i></h2></div>'],
['future','15 / 20','14 — o que eu quero','<h2>não quero só<br><i>lembranças.</i></h2><div class="future-grid"><div><span>quero</span><b>mais domingos.</b></div><div><span>quero</span><b>mais viagens.</b></div><div><span>quero</span><b>mais histórias.</b></div><div><span>quero</span><b>mais você.</b></div></div>'],
['envelope','16 / 20','15 — antes da pergunta','<div class="envelope"><div class="envelope-letter"><p>se você chegou até aqui, já sabe que eu pensei muito em como fazer isso.</p><p>mas a verdade é que nenhuma página consegue dizer tudo o que eu sinto.</p><p class="emphasis">então eu vou perguntar do jeito mais simples que existe.</p></div></div>'],
['reveal','17 / 20','16 — falta pouco','<div class="reveal-card"><span>uma última coisa</span><h2>fecha os olhos por um segundo.</h2><p>agora abre.</p><button id="reveal" class="outline">continuar</button></div>'],
['finalphoto','18 / 20','17 — a nossa história','<div class="final-polaroid"><div class="photo" data-src="assets/images/foto-final.jpg">nossa foto favorita</div><p>19.07.2026 — e tudo que veio depois.</p></div><p class="final-intro">eu não sei o que vai acontecer nas próximas páginas da nossa história.</p><p class="final-intro strong">mas eu sei com quem eu quero descobrir.</p>'],
['proposal','19 / 20','18 — a pergunta','<span class="proposal-small">alissa,</span><h2>quer<br><i>namorar comigo?</i></h2><div class="actions"><button id="yes" class="yes">sim</button><button id="no" class="no">não</button></div><p id="hint" class="hint">pensa com carinho. eu já pensei.</p>'],
['success','20 / 20','19 — a nossa próxima página','<div class="ring"></div><h2>então é<br><i>nós.</i></h2><p>eu escolheria você de novo, em qualquer história.</p><p class="success-date">19.07.2026 → para sempre</p><div class="success-photo"><div class="photo" data-src="assets/images/foto-success.jpg">nossa foto aqui</div></div><p class="end">fim desta página.<br>começo da nossa história.</p>']
];
const lock=document.getElementById('lock'),book=document.getElementById('book');
function build(){book.innerHTML='<nav class="progress"><span>para alissa</span><div class="progress-line"><span id="fill"></span></div><span id="num">01 / 20</span></nav>'+pages.map((p,i)=>`<section class="page ${p[0]}" data-index="${i}"><div class="page-inner">${p[2].includes('—')?`<p class="chapter">${p[2]}</p>`:''}${p[3]}</div></section>`).join('');
 document.querySelectorAll('.photo[data-src]').forEach(el=>{const src=el.dataset.src;const img=new Image();img.onload=()=>{el.style.backgroundImage=`url("${src}")`;el.textContent='';};img.src=src});
 const start=new Date('2026-07-19T00:00:00');function counter(){let d=Math.max(0,Date.now()-start);document.getElementById('days').textContent=Math.floor(d/864e5);document.getElementById('hours').textContent=Math.floor(d%864e5/36e5);document.getElementById('mins').textContent=Math.floor(d%36e5/6e4)}counter();setInterval(counter,60000);
 const music=document.getElementById('music'),mb=document.getElementById('musicBtn');mb.onclick=async()=>{try{if(music.paused){await music.play();mb.textContent='pausar música'}else{music.pause();mb.textContent='tocar música'}}catch{mb.textContent='adicione sua música'}};
 document.getElementById('reveal').onclick=()=>document.querySelector('[data-index="18"]').scrollIntoView({behavior:'smooth'});setupProposal();
 const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const i=+e.target.dataset.index;document.getElementById('fill').style.width=((i+1)/20*100)+'%';document.getElementById('num').textContent=String(i+1).padStart(2,'0')+' / 20'}}),{threshold:.55});document.querySelectorAll('.page').forEach(x=>observer.observe(x));
}
function setupProposal(){const yes=document.getElementById('yes'),no=document.getElementById('no'),hint=document.getElementById('hint');let scale=1;const dodge=()=>{scale=Math.min(scale+0.18,3.8);yes.style.transform=`scale(${scale})`;no.style.position='absolute';no.style.left=Math.random()*70+15+'%';no.style.top=Math.random()*65+15+'%';hint.textContent=['esse botão está ficando difícil de escolher.','acho que o destino está tentando ajudar.','você pode tentar de novo.'][Math.floor(Math.random()*3)]};no.addEventListener('mouseenter',dodge);no.addEventListener('touchstart',e=>{e.preventDefault();dodge()},{passive:false});no.addEventListener('click',dodge);yes.onclick=()=>document.querySelector('[data-index="19"]').scrollIntoView({behavior:'smooth'});}
let entered='';const dots=[...document.querySelectorAll('#pin span')];function renderPin(){dots.forEach((d,i)=>d.classList.toggle('filled',i<entered.length))}function tryPassword(){if(entered==='19072026'){lock.classList.add('unlocking');setTimeout(()=>{lock.style.display='none';book.hidden=false;build();window.scrollTo(0,0)},650)}else{document.getElementById('error').textContent='essa não é a data. tenta lembrar com carinho.';dots.forEach(d=>d.classList.add('shake'));setTimeout(()=>dots.forEach(d=>d.classList.remove('shake')),350);entered='';renderPin()}}
document.querySelectorAll('.keypad button').forEach(btn=>btn.addEventListener('click',()=>{const key=btn.dataset.key;if(key==='back')entered=entered.slice(0,-1);else if(key==='clear')entered='';else if(entered.length<8)entered+=key;document.getElementById('error').textContent='';renderPin();if(entered.length===8)setTimeout(tryPassword,160)}));
document.addEventListener('keydown',e=>{if(lock.style.display==='none')return;if(/^[0-9]$/.test(e.key)){if(entered.length<8)entered+=e.key}else if(e.key==='Backspace')entered=entered.slice(0,-1);renderPin();if(entered.length===8)setTimeout(tryPassword,160)});renderPin();